### ISSUE TITLE
Add Behat Extension class instead of Context

### ISSUE THREAD

**Issue by fauxalgore** [fauxalgore/BehatSayExtension#2]

**Comment by stevector** [comment]
Hi @fauxalgore,

A context might not be necessary at all. Here is a Behat extension that uses an EventSubscriber and no Context class: https://github.com/adamquaile/behat-command-runner-extension/blob/master/src/AdamQuaile/Behat/CommandRunnerExtension/CommandRunnerSubscriber.php

**Comment by fauxalgore** [comment]
Thanks @stevector. I will have a pull request soon that uses this convention.

**Comment by fauxalgore** [comment]
Follow up: https://github.com/fauxalgore/BehatSayExtension/issues/7
